create table if not exists jec.ransen_match_history (
  id bigint generated by default as identity primary key,
  room_id text not null,
  match_number bigint not null,
  status text not null check (status in ('completed', 'interrupted')),
  termination_reason text not null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  last_snapshot_at timestamptz not null,
  duration_seconds integer not null check (duration_seconds >= 0),
  human_count integer not null default 0,
  bot_count integer not null default 0,
  participants jsonb not null default '[]'::jsonb,
  winners jsonb not null default '[]'::jsonb,
  losers jsonb not null default '[]'::jsonb,
  provisional_leaders jsonb not null default '[]'::jsonb,
  surviving_participants jsonb not null default '[]'::jsonb,
  events jsonb not null default '[]'::jsonb,
  final_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (room_id, match_number),
  unique (room_id, started_at)
);

create index if not exists ransen_match_history_room_match_idx
  on jec.ransen_match_history (room_id, match_number desc);

alter table jec.ransen_match_history enable row level security;
revoke all on table jec.ransen_match_history from anon, authenticated;
grant select, insert, update, delete on table jec.ransen_match_history to service_role;
grant usage, select on sequence jec.ransen_match_history_id_seq to service_role;

create or replace function jec.archive_ransen_match()
returns trigger
language plpgsql
set search_path = pg_catalog, jec
as $$
declare
  match_snapshot jsonb;
  started_ms numeric;
  match_started_at timestamptz;
  match_ended_at timestamptz;
  next_match_number bigint;
  match_status text;
  reason text;
  all_participants jsonb := '[]'::jsonb;
  winner_participants jsonb := '[]'::jsonb;
  loser_participants jsonb := '[]'::jsonb;
  leader_participants jsonb := '[]'::jsonb;
  alive_participants jsonb := '[]'::jsonb;
  archived_events jsonb := '[]'::jsonb;
  humans integer := 0;
  bots integer := 0;
begin
  if old.phase <> 'PLAYING' or new.phase = 'PLAYING' then
    return new;
  end if;

  match_snapshot := case when new.phase = 'THEATER' then new.snapshot else old.snapshot end;
  started_ms := nullif(match_snapshot ->> 'startedAt', '')::numeric;
  if started_ms is null or jsonb_typeof(match_snapshot -> 'slimes') <> 'array' then
    return new;
  end if;

  match_started_at := to_timestamp(started_ms / 1000.0);
  match_ended_at := coalesce(new.updated_at, now());
  match_status := case when new.phase = 'THEATER' then 'completed' else 'interrupted' end;
  reason := case
    when new.phase = 'OFF' then 'manual_off'
    when new.phase = 'LOBBY' then 'manual_restart'
    when match_snapshot ->> 'endReason' = 'last_slime' then 'last_slime'
    else 'timeout'
  end;
  archived_events := coalesce(match_snapshot -> 'auditEvents', '[]'::jsonb);
  if not exists (
    select 1 from jsonb_array_elements(archived_events) event
    where event ->> 'type' = 'match_ended'
  ) then
    archived_events := archived_events || jsonb_build_array(jsonb_build_object(
      'id', 'match-ended:server-' || floor(extract(epoch from match_ended_at) * 1000)::bigint,
      'type', 'match_ended',
      'at', floor(extract(epoch from match_ended_at) * 1000)::bigint,
      'details', jsonb_build_object('reason', reason)
    ));
  end if;

  with members as (
    select
      member ->> 'id' as id,
      coalesce(nullif(member ->> 'name', ''), 'Unknown') as name,
      coalesce((member ->> 'isBot')::boolean, false) as is_bot,
      row_number() over (partition by member ->> 'id' order by slime_ordinality desc) as rn
    from jsonb_array_elements(match_snapshot -> 'slimes') with ordinality s(slime, slime_ordinality)
    cross join lateral jsonb_array_elements(s.slime -> 'members') member
    where nullif(member ->> 'id', '') is not null
  )
  select
    coalesce(jsonb_agg(jsonb_build_object(
      'id', id,
      'name', name,
      'participantType', case when is_bot then 'bot' else 'human' end
    ) order by name) filter (where rn = 1), '[]'::jsonb),
    count(*) filter (where rn = 1 and not is_bot),
    count(*) filter (where rn = 1 and is_bot)
  into all_participants, humans, bots
  from members;

  with ranked_alive as (
    select slime, row_number() over (
      order by coalesce((slime ->> 'size')::numeric, 0) desc, slime ->> 'id'
    ) as rank
    from jsonb_array_elements(match_snapshot -> 'slimes') slime
    where coalesce((slime ->> 'isDead')::boolean, false) = false
      and jsonb_array_length(coalesce(slime -> 'members', '[]'::jsonb)) > 0
  ),
  leader_members as (
    select member ->> 'id' as id
    from ranked_alive
    cross join lateral jsonb_array_elements(slime -> 'members') member
    where rank = 1
  )
  select coalesce(jsonb_agg(participant), '[]'::jsonb)
  into leader_participants
  from jsonb_array_elements(all_participants) participant
  where participant ->> 'id' in (select id from leader_members);

  with alive_ids as (
    select member ->> 'id' as id
    from jsonb_array_elements(match_snapshot -> 'slimes') slime
    cross join lateral jsonb_array_elements(slime -> 'members') member
    where coalesce((slime ->> 'isDead')::boolean, false) = false
  )
  select coalesce(jsonb_agg(participant), '[]'::jsonb)
  into alive_participants
  from jsonb_array_elements(all_participants) participant
  where participant ->> 'id' in (select id from alive_ids);

  if match_status = 'completed' then
    winner_participants := leader_participants;
    select coalesce(jsonb_agg(participant), '[]'::jsonb)
    into loser_participants
    from jsonb_array_elements(all_participants) participant
    where not exists (
      select 1 from jsonb_array_elements(winner_participants) winner
      where winner ->> 'id' = participant ->> 'id'
    );
    leader_participants := '[]'::jsonb;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(new.id, 0));
  select coalesce(max(match_number), 0) + 1
  into next_match_number
  from jec.ransen_match_history
  where room_id = new.id;

  insert into jec.ransen_match_history (
    room_id, match_number, status, termination_reason, started_at, ended_at,
    last_snapshot_at, duration_seconds, human_count, bot_count, participants,
    winners, losers, provisional_leaders, surviving_participants, events, final_snapshot
  ) values (
    new.id,
    next_match_number,
    match_status,
    reason,
    match_started_at,
    match_ended_at,
    case when new.phase = 'THEATER' then match_ended_at else coalesce(old.updated_at, match_ended_at) end,
    greatest(0, floor(extract(epoch from (match_ended_at - match_started_at)))::integer),
    humans,
    bots,
    all_participants,
    winner_participants,
    loser_participants,
    leader_participants,
    alive_participants,
    archived_events,
    match_snapshot
  )
  on conflict (room_id, started_at) do nothing;

  return new;
end;
$$;

revoke all on function jec.archive_ransen_match() from public, anon, authenticated;
grant execute on function jec.archive_ransen_match() to service_role;

drop trigger if exists archive_ransen_match_on_phase_change on jec.ransen_rooms;
create trigger archive_ransen_match_on_phase_change
after update of phase on jec.ransen_rooms
for each row
execute function jec.archive_ransen_match();
